In [15]:
import pandas as pd
df=pd.read_csv(r"C:\Users\PATHAN MUBESHIRA\Downloads\data.csv")
df

,Unnamed: 0,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
0,2,1002,228.0,92,37.0,6.2,4.640000,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0
1,6,1011,195.0,92,41.0,4.8,4.840000,Buckingham,30,male,69.0,191.0,medium,161.0,112.0,161.0,112.0,46.0,49.0,720.0
2,8,1016,177.0,87,49.0,3.6,4.840000,Buckingham,45,male,69.0,166.0,large,160.0,80.0,128.0,86.0,34.0,40.0,300.0
3,10,1024,242.0,82,54.0,4.5,4.770000,Louisa,60,female,65.0,156.0,medium,130.0,90.0,130.0,90.0,39.0,45.0,300.0
4,15,1036,213.0,83,47.0,4.5,3.410000,Louisa,33,female,65.0,157.0,medium,130.0,90.0,120.0,96.0,37.0,41.0,240.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,394,41254,169.0,104,58.0,2.9,4.820000,Louisa,25,female,60.0,154.0,medium,140.0,95.0,130.0,94.0,40.0,42.0,60.0
126,395,41500,179.0,85,50.0,3.6,4.990000,Louisa,37,male,66.0,136.0,medium,190.0,94.0,172.0,100.0,33.0,39.0,480.0
127,397,41503,301.0,90,118.0,2.6,4.280000,Louisa,89,female,61.0,115.0,medium,218.0,90.0,238.0,90.0,31.0,41.0,210.0
128,398,41506,296.0,369,46.0,6.4,16.110001,Louisa,53,male,69.0,173.0,medium,138.0,94.0,130.0,94.0,35.0,39.0,210.0
129,399,41507,284.0,89,54.0,5.3,4.390000,Louisa,51,female,63.0,154.0,medium,140.0,100.0,146.0,102.0,32.0,43.0,180.0

In [16]:
shape = df.shape
print("Shape of the DataFrame:", shape)

Shape of the DataFrame: (130, 20)

In [17]:
size = df.size
print("Size of the DataFrame:", size)

Size of the DataFrame: 2600

In [21]:
quantiles = df['chol'].describe(percentiles=[0.25, 0.75])

q1 = quantiles['25%']
q3 = quantiles['75%']

print("25th Quantile (Q1):", q1)
print("75th Quantile (Q3):", q3)

25th Quantile (Q1): 184.25
75th Quantile (Q3): 241.5

In [23]:
dot_product = np.dot(height, weight)

print("Dot Product of Height and Weight:", dot_product)

NameError: name 'height' is not defined

In [26]:
percentile_25 = np.percentile("bp.1d", 25)
percentile_75 = np.percentile("bp.1d", 75)

print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U5'), dtype('<U5')) -> None

In [28]:
filtered_hdl = hdl_data[hdl < 50]

# Calculate the median of the filtered 'hdl' data
median_hdl = np.median(filtered_hdl)

print("Median of 'hdl' where 'hdl' is less than 50:", median_hdl)

NameError: name 'hdl_data' is not defined

In [29]:
import numpy as np

# Replace these arrays with your actual data
bp_1s = np.array([120, 122, 125, 130, 135, 140, 145, 150, 155, 160])
bp_2s = np.array([120, 122, 130, 130, 135, 142, 145, 148, 155, 160])

# Create a new array with 1s where the condition is met and 0s otherwise
new_array = np.where(bp_1s == bp_2s, 1, 0)

print("New Array based on the condition:", new_array)

New Array based on the condition: [1 1 0 1 1 0 1 0 1 1]